import test from "node:test";import assert from "node:assert/strict";
function canApprove(comments){return comments.every(comment=>comment.resolved)}
function invoiceEligible(entries){return entries.filter(entry=>entry.billable&&!entry.invoiced)}
function invoiceTotal(entries){return invoiceEligible(entries).reduce((sum,entry)=>sum+entry.minutes/60*entry.hourlyRate,0)}
test("approval is blocked while any redline remains open",()=>{assert.equal(canApprove([{resolved:true},{resolved:false}]),false);assert.equal(canApprove([{resolved:true},{resolved:true}]),true)});
test("invoice excludes previously invoiced time",()=>{const entries=[{minutes:60,hourlyRate:100,billable:true,invoiced:false},{minutes:120,hourlyRate:100,billable:true,invoiced:true},{minutes:30,hourlyRate:100,billable:false,invoiced:false}];assert.equal(invoiceEligible(entries).length,1);assert.equal(invoiceTotal(entries),100)});
test("second invoice pass has no eligible entries",()=>{const first=[{minutes:90,hourlyRate:120,billable:true,invoiced:false}];assert.equal(invoiceTotal(first),180);const after=first.map(entry=>({...entry,invoiced:true}));assert.equal(invoiceTotal(after),0)});
test("missing brief facts stay explicit",()=>{const fields={objective:"Launch campaign",timeline:"Needs client input"};assert.equal(fields.timeline,"Needs client input");assert.notEqual(fields.timeline,"ASAP")});
test("pin coordinates remain inside normalized proof bounds",()=>{const normalize=(value,size)=>Number(Math.max(0,Math.min(100,value/size*100)).toFixed(1));assert.equal(normalize(250,1000),25);assert.equal(normalize(-10,1000),0);assert.equal(normalize(1200,1000),100)});
test("uploading a new version advances review state",()=>{const current={version:3,status:"Approved"};const uploaded={version:current.version+1,status:"In review"};assert.deepEqual(uploaded,{version:4,status:"In review"})});
test("timer saves at least one billable minute",()=>{const savedMinutes=seconds=>Math.max(1,Math.round(seconds/60));assert.equal(savedMinutes(1),1);assert.equal(savedMinutes(89),1);assert.equal(savedMinutes(91),2)});
test("eligible invoice total updates after new time",()=>{const entries=[{minutes:60,hourlyRate:130,billable:true,invoiced:false},{minutes:30,hourlyRate:130,billable:true,invoiced:false}];assert.equal(invoiceTotal(entries),195)});
test("resolved comments can be reopened before approval",()=>{const comment={resolved:true};const reopened={...comment,resolved:!comment.resolved};assert.equal(canApprove([reopened]),false)});
test("wallet signatures reject tampered challenges",async()=>{const{Keypair}=await import("@solana/web3.js");const nacl=(await import("tweetnacl")).default;const wallet=Keypair.generate();const message=new TextEncoder().encode("Briefrail wallet verification\nNetwork: Solana devnet");const signature=nacl.sign.detached(message,wallet.secretKey);assert.equal(nacl.sign.detached.verify(message,signature,wallet.publicKey.toBytes()),true);assert.equal(nacl.sign.detached.verify(new TextEncoder().encode("tampered"),signature,wallet.publicKey.toBytes()),false)});
test("on-chain receipt requires the configured attestor",()=>{const configured="35z7X59rtyts557Up1RAwpyYN7x2cFqcDc7RjPuNxFzr";const transactionSigner="35z7X59rtyts557Up1RAwpyYN7x2cFqcDc7RjPuNxFzr";assert.equal(transactionSigner===configured,true);assert.equal("11111111111111111111111111111111"===configured,false)});